services:
  autok_generalasa:
    image: php:8.3.8-cli-alpine3.20
    working_dir: /app
    volumes:
      - .:/app
    command: php auto_generator.php 450 csv

  szemely_generalasa:
    image: php:8.3.8-cli-alpine3.20
    working_dir: /app
    volumes:
      - .:/app
    command: php szemely_generator.php 1000 csv
    depends_on:
      - autok_generalasa

  lezart_berles_generator:
    image: php:8.3.8-cli-alpine3.20
    working_dir: /app
    volumes:
      - .:/app
    command: php lezart_berlesek_generator.php 2750 csv
    depends_on:
      - szemely_generalasa