<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PriceSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('prices')->insert([
            # E-up              18 kW       1-es besorolas
            # Renault Kangoo    33 kW       2-es besorolas
            # E-up & Citigo     36 kW       3-as besorolas
            # Kia Niro          65 kW       4-es besorolas
            # Opel Vivaro       75 kW       5-ös besorolas

            # null -> nem elérhető ≠ 0!

            ## [Power] árak * [5 category_id]
            # E-up | 18 kW | 1-es besorolas |
            [
                'sub_id' => 1,
                'category_class' => 1,
                'rental_start' => 380,
                'driving_minutes' => 105,
                'discounted_driving' => null,
                'parking_minutes' => 85,
                'reserv_minutes' => 85,
                'disc_parking_minutes' => 55,
                'daily_fee' => 17680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => 2490,
                'airport_in_fee' => 990,
                'airport_out_terminal_fee' => 3190,
                'airport_in_terminal_fee' => 1680,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 390,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
                'weekend_daily_fee' => null,
            ],
            # Renault Kangoo | 33 kW | 2-es besorolas |
            [
                'sub_id' => 1,
                'category_class' => 2,
                'rental_start' => 380,
                'driving_minutes' => 105,
                'discounted_driving' => null,
                'parking_minutes' => 85,
                'reserv_minutes' => 85,
                'disc_parking_minutes' => 55,
                'daily_fee' => 23680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
                'weekend_daily_fee' => null,
            ],
            # E-up, Citigo | 36kW | 3-as besorolas |
            [
                'sub_id' => 1,
                'category_class' => 3,
                'rental_start' => 380,
                'driving_minutes' => 105,
                'discounted_driving' => null,
                'parking_minutes' => 85,
                'reserv_minutes' => 85,
                'disc_parking_minutes' => 55,
                'daily_fee' => 18680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => 2490,
                'airport_in_fee' => 990,
                'airport_out_terminal_fee' => 3190,
                'airport_in_terminal_fee' => 1680,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 390,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
                'weekend_daily_fee' => null,
            ],
            # Kia Niro | 65 kW | 4-es besorolas |
            [
                'sub_id' => 1,
                'category_class' => 4,
                'rental_start' => 1990,
                'driving_minutes' => 78,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => 78,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 25680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
                'weekend_daily_fee' => null,
            ],
            # Opel Vivaro | 75 kW | 5-ös besorolas |
            [
                'sub_id' => 1,
                'category_class' => 5,
                'rental_start' => 1990,
                'driving_minutes' => 69,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => 69,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 22678,
                'daily_km_limit' => 15,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => 12473,
                'six_hour_fee' => 15875,
                'twelve_hour_fee' => 19276,
                'weekend_daily_fee' => null,
            ],
            ####################################
            ## [Power-Plus] árak * [5 category_id]
            # E-up | 18 kW | 1-es besorolas |
            [
                'sub_id' => 2,
                'category_class' => 1,
                'rental_start' => 290,
                'driving_minutes' => 83,
                'discounted_driving' => null,
                'parking_minutes' => 59,
                'reserv_minutes' => 59,
                'disc_parking_minutes' => 35,
                'daily_fee' => 14680,
                'weekend_daily_fee' => 10680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => 2490,
                'airport_in_fee' => 990,
                'airport_out_terminal_fee' => 3190,
                'airport_in_terminal_fee' => 1680,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 390,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Renault Kangoo - 33 kW
            [
                'sub_id' => 2,
                'category_class' => 2,
                'rental_start' => 290,
                'driving_minutes' => 83,
                'discounted_driving' => null,
                'parking_minutes' => 59,
                'reserv_minutes' => 59,
                'disc_parking_minutes' => 35,
                'daily_fee' => 20680,
                'weekend_daily_fee' => 20680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # E-up, Citigo | 36kW | 3-as besorolas |
            [
                'sub_id' => 2,
                'category_class' => 3,
                'rental_start' => 290,
                'driving_minutes' => 83,
                'discounted_driving' => null,
                'parking_minutes' => 59,
                'reserv_minutes' => 59,
                'disc_parking_minutes' => 35,
                'daily_fee' => 15680,
                'weekend_daily_fee' => 11680,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => 2490,
                'airport_in_fee' => 990,
                'airport_out_terminal_fee' => 3190,
                'airport_in_terminal_fee' => 1680,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 390,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Kia Niro | 65 kW | 4-es besorolas |
            [ ## 46350 +
                'sub_id' => 2,
                'category_class' => 4,
                'rental_start' => 1990,
                'driving_minutes' => 78,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => 78,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 22680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Opel Vivaro | 75 kW | 5-ös besorolas |
            [
                'sub_id' => 2,
                'category_class' => 5,
                'rental_start' => 1990,
                'driving_minutes' => 69,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => 69,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 20128,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 15,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => 11070,
                'six_hour_fee' => 14090,
                'twelve_hour_fee' => 17109,
            ],
            #######################################
            ## [Power-Prémium] árak * [5 category_id]
            # E-up | 18 kW | 1-es besorolas |
            [
                'sub_id' => 3,
                'category_class' => 1,
                'rental_start' => 290,
                'driving_minutes' => 83,
                'discounted_driving' => null,
                'parking_minutes' => 59,
                'reserv_minutes' => 59,
                'disc_parking_minutes' => 35,
                'daily_fee' => 14680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => 2490,
                'airport_in_fee' => 990,
                'airport_out_terminal_fee' => 3190,
                'airport_in_terminal_fee' => 1680,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 390,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Renault Kangoo - 33 kW
            [
                'sub_id' => 3,
                'category_class' => 2,
                'rental_start' => 290,
                'driving_minutes' => 78,
                'discounted_driving' => null,
                'parking_minutes' => 59,
                'reserv_minutes' => 59,
                'disc_parking_minutes' => 35,
                'daily_fee' => 14680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # E-up, Citigo | 36kW | 3-as besorolas |
            [
                'sub_id' => 3,
                'category_class' => 3,
                'rental_start' => 1990,
                'driving_minutes' => 59,
                'discounted_driving' => null,
                'parking_minutes' => 59,
                'reserv_minutes' => 59,
                'disc_parking_minutes' => 35,
                'daily_fee' => 15680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Kia Niro | 65 kW | 4-es besorolas |
            [
                'sub_id' => 3,
                'category_class' => 4,
                'rental_start' => 1990,
                'driving_minutes' => 78,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => 78,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 22680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 100,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Opel Vivaro | 75 kW | 5-ös besorolas |
            [
                'sub_id' => 3,
                'category_class' => 5,
                'rental_start' => 1990,
                'driving_minutes' => 78,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => 78,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 20128,
                'daily_km_limit' => 15,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => 11070,
                'six_hour_fee' => 14090,
                'twelve_hour_fee' => 17109,
                'weekend_daily_fee' => null,
            ],
            ###################################
            ## [Power-VIP] árak * [5 category_id]
            # E-up | 18 kW | 1-as besorolas |
            [
                'sub_id' => 4,
                'category_class' => 1,
                'rental_start' => 250,
                'driving_minutes' => 58,
                'discounted_driving' => 50,
                'parking_minutes' => 41,
                'reserv_minutes' => 41,
                'disc_parking_minutes' => 24,
                'daily_fee' => 13680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 125,
                'km_fee' => 48,
                'airport_out_fee' => 1245,
                'airport_in_fee' => 495,
                'airport_out_terminal_fee' => 2490,
                'airport_in_terminal_fee' => 990,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 0,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Renault Kangoo - 33 kW
            [
                'sub_id' => 4,
                'category_class' => 2,
                'rental_start' => 250,
                'driving_minutes' => 58,
                'discounted_driving' => null,
                'parking_minutes' => 41,
                'reserv_minutes' => 41,
                'disc_parking_minutes' => 24,
                'daily_fee' => 19680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 125,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # E-up, Citigo | 36kW | 3-as besorolas |
            [
                'sub_id' => 4,
                'category_class' => 3,
                'rental_start' => 250,
                'driving_minutes' => 58,
                'discounted_driving' => 50,
                'parking_minutes' => 41,
                'reserv_minutes' => 41,
                'disc_parking_minutes' => 24,
                'daily_fee' => 14680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 125,
                'km_fee' => 48,
                'airport_out_fee' => 1245,
                'airport_in_fee' => 495,
                'airport_out_terminal_fee' => 2490,
                'airport_in_terminal_fee' => 990,
                'zone_opening_fee' => 0,
                'zone_closing_fee' => 0,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Kia Niro | 65 kW | 4-es besorolas |
            [
                # 22670
                'sub_id' => 4,
                'category_class' => 4,
                'rental_start' => 1990,
                'driving_minutes' => 78,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => null,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 20680,
                'weekend_daily_fee' => null,
                'daily_km_limit' => 125,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => null,
                'six_hour_fee' => null,
                'twelve_hour_fee' => null,
            ],
            # Opel Vivaro | 75 kW | 5-ös besorolas |
            [
                'sub_id' => 4,
                'category_class' => 5,
                'rental_start' => 1990,
                'driving_minutes' => 78,           # Csak ha a 24 órán túl (napi bérlés minimum! túlmegy akkor pluszban.)
                'discounted_driving' => null,
                'parking_minutes' => null,
                'reserv_minutes' => null,
                'disc_parking_minutes' => null,
                'daily_fee' => 20128,
                'daily_km_limit' => 15,
                'km_fee' => 48,
                'airport_out_fee' => null,
                'airport_in_fee' => null,
                'airport_out_terminal_fee' => null,
                'airport_in_terminal_fee' => null,
                'zone_opening_fee' => null,
                'zone_closing_fee' => null,
                'three_hour_fee' => 10603,
                'six_hour_fee' => 13495,
                'weekend_daily_fee' => null,
                'twelve_hour_fee' => null,
            ],
        ]);
    }
}
