server {

    server_name frontend.localhost;
    listen 80;

     location / {
        proxy_pass http://frontend:5173/;

        error_page 502 /502.html;
        location = /502.html {
            return 200 '<html><body><h1>502 - Fut a Frontend?</h1></body></html>';
            internal;
        }
    }

}