version: '3.8'

services:
  composer_install:
    build: .
    working_dir: /app
    command: /bin/sh -c "composer install && tail -f /dev/null"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "test", "-f", "/app/vendor/autoload.php"]
      interval: 5s
      timeout: 30s
      retries: 10

  flotta_generalasa:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "while [ ! -f /app/vendor/autoload.php ]; do sleep 1; done; php flotta_generator.php"]
    depends_on:
      composer_install:
        condition: service_healthy

  autok_generalasa:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "while [ ! -f /app/vendor/autoload.php ]; do sleep 1; done; php auto_generator.php 200"]
    depends_on:
      flotta_generalasa:
        condition: service_started
