# Automatikusan futtatja a Dockerfile-t

version: '3.8'

services:
  php:                        # Felcsatolandó szolgáltatások [2 szóközzel beljebb kezdeni!]
    build: .                  # Docker-t, magát építse fel. [4 szóközzel beljebb kezdeni]
    volumes:                  # [4 szóközzel beljebb kezdeni]
      - .:/app                # Aktuális mappától számítva, hol dolgozzon[ 6 szóköz + kötőjel + létrehozott mappa neve]
    working_dir: /app         # Mappa, amiben dolgozni fogunk. [4 szóközzel beljebb kezdeni]
    command: php index.php    # futtató modul, futtatandó fájl neve, kezdő fájl. Megegyezik a CMD-ben található paraméterekkel. [4 szóközzel beljebb kezdeni]